"""create_all_tables

Revision ID: 4251bc619373
Revises: 001
Create Date: 2026-07-17 11:05:04.058628+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import geoalchemy2

# revision identifiers, used by Alembic.
revision: str = '4251bc619373'
down_revision: Union[str, Sequence[str], None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('destinations',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=512), nullable=False),
    sa.Column('osm_place_id', sa.String(length=100), nullable=True),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lng', sa.Float(), nullable=False),
    sa.Column('place_count', sa.Integer(), nullable=False),
    sa.Column('enriched_count', sa.Integer(), nullable=False),
    sa.Column('indexed_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_destinations_osm_place_id'), 'destinations', ['osm_place_id'], unique=True)
    op.create_table('users',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('avatar_url', sa.String(length=2048), nullable=True),
    sa.Column('google_id', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_google_id'), 'users', ['google_id'], unique=True)
    op.create_table('places',
    sa.Column('osm_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('location', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('destination_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['destination_id'], ['destinations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('osm_id')
    )
    op.create_index('ix_places_destination_category', 'places', ['destination_id', 'category'], unique=False)
    op.create_index(op.f('ix_places_destination_id'), 'places', ['destination_id'], unique=False)
    op.create_table('trips',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('session_id', sa.String(length=64), nullable=False),
    sa.Column('destination_id', sa.UUID(), nullable=False),
    sa.Column('days', sa.Integer(), nullable=False),
    sa.Column('preferences', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'COMPLETE', 'FAILED', name='trip_status'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['destination_id'], ['destinations.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trips_destination_id'), 'trips', ['destination_id'], unique=False)
    op.create_index(op.f('ix_trips_session_id'), 'trips', ['session_id'], unique=False)
    op.create_index('ix_trips_user_created', 'trips', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_trips_user_id'), 'trips', ['user_id'], unique=False)
    op.create_table('trip_evaluations',
    sa.Column('trip_id', sa.UUID(), nullable=True),
    sa.Column('destination_id', sa.UUID(), nullable=False),
    sa.Column('raw_input', sa.Text(), nullable=False),
    sa.Column('parsed_preferences', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('candidates_retrieved', sa.Integer(), nullable=False),
    sa.Column('candidates_after_ranking', sa.Integer(), nullable=False),
    sa.Column('final_route', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('places_per_day', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('total_distance_km', sa.Float(), nullable=False),
    sa.Column('base_lat', sa.Float(), nullable=False),
    sa.Column('base_lng', sa.Float(), nullable=False),
    sa.Column('generation_time_ms', sa.Integer(), nullable=False),
    sa.Column('token_usage', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('llm_model', sa.String(length=255), nullable=False),
    sa.Column('llm_retry_count', sa.Integer(), nullable=False),
    sa.Column('tool_loop_count', sa.Integer(), nullable=False),
    sa.Column('tool_trace', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('agent_phase_reached', sa.String(length=50), nullable=False),
    sa.Column('readiness_score', sa.Float(), nullable=True),
    sa.Column('used_geo_fallback', sa.Boolean(), nullable=False),
    sa.Column('used_osrm_fallback', sa.Boolean(), nullable=False),
    sa.Column('abort_triggered', sa.Boolean(), nullable=False),
    sa.Column('validation_passed', sa.Boolean(), nullable=False),
    sa.Column('validation_warnings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('user_saved', sa.Boolean(), nullable=False),
    sa.Column('user_edited', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['destination_id'], ['destinations.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_trip_eval_abort', 'trip_evaluations', ['abort_triggered'], unique=False)
    op.create_index('ix_trip_eval_dest_created', 'trip_evaluations', ['destination_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_trip_evaluations_destination_id'), 'trip_evaluations', ['destination_id'], unique=False)
    op.create_index(op.f('ix_trip_evaluations_trip_id'), 'trip_evaluations', ['trip_id'], unique=False)
    op.create_table('trip_places',
    sa.Column('trip_id', sa.UUID(), nullable=False),
    sa.Column('place_id', sa.UUID(), nullable=False),
    sa.Column('day_number', sa.Integer(), nullable=False),
    sa.Column('order_in_day', sa.Integer(), nullable=False),
    sa.Column('travel_time_min', sa.Integer(), nullable=False),
    sa.Column('visit_duration_min', sa.Integer(), nullable=False),
    sa.Column('suggested_start_time', sa.String(length=5), nullable=True),
    sa.Column('arrival_note', sa.String(length=512), nullable=True),
    sa.Column('polyline', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['place_id'], ['places.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trip_id', 'place_id', name='uq_trip_place')
    )
    op.create_index('ix_trip_places_trip_day', 'trip_places', ['trip_id', 'day_number'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_trip_places_trip_day', table_name='trip_places')
    op.drop_table('trip_places')
    op.drop_index(op.f('ix_trip_evaluations_trip_id'), table_name='trip_evaluations')
    op.drop_index(op.f('ix_trip_evaluations_destination_id'), table_name='trip_evaluations')
    op.drop_index('ix_trip_eval_dest_created', table_name='trip_evaluations')
    op.drop_index('ix_trip_eval_abort', table_name='trip_evaluations')
    op.drop_table('trip_evaluations')
    op.drop_index(op.f('ix_trips_user_id'), table_name='trips')
    op.drop_index('ix_trips_user_created', table_name='trips')
    op.drop_index(op.f('ix_trips_session_id'), table_name='trips')
    op.drop_index(op.f('ix_trips_destination_id'), table_name='trips')
    op.drop_table('trips')
    op.drop_index(op.f('ix_places_destination_id'), table_name='places')
    op.drop_index('ix_places_destination_category', table_name='places')
    op.drop_table('places')
    op.drop_index(op.f('ix_users_google_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_destinations_osm_place_id'), table_name='destinations')
    op.drop_table('destinations')
    # ### end Alembic commands ###
