"""add_trip_edit_events

Revision ID: 6e0f01af33c5
Revises: 4251bc619373
Create Date: 2026-07-21 13:47:37.202273+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6e0f01af33c5'
down_revision: Union[str, Sequence[str], None] = '4251bc619373'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trip_edit_events',
    sa.Column('trip_id', sa.UUID(), nullable=False),
    sa.Column('edit_type', sa.Enum('REORDER', 'REMOVE_STOP', 'ADD_STOP', 'REOPTIMIZE_DAY', name='edit_type'), nullable=False),
    sa.Column('day_number', sa.Integer(), nullable=True),
    sa.Column('place_id', sa.UUID(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['place_id'], ['places.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_trip_edit_events_trip_created', 'trip_edit_events', ['trip_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_trip_edit_events_trip_id'), 'trip_edit_events', ['trip_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trip_edit_events_trip_id'), table_name='trip_edit_events')
    op.drop_index('ix_trip_edit_events_trip_created', table_name='trip_edit_events')
    op.drop_table('trip_edit_events')
    # ### end Alembic commands ###
